export const options = [
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
  { value: "Batik", label: "Batik" },
  { value: "Cartooning", label: "Cartooning" },
  { value: "Crafting", label: "Crafting" },
  { value: "Digital Art", label: "Digital Art" },
  { value: "Drawing", label: "Drawing" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Mandala", label: "Mandala" },
  { value: "Metal Painting", label: "Metal Painting" },
];
